config/routes.rb
Rails.application.routes.draw do
     root 'users/items#index'
  namespace :users, :path => ""  do
    resources :items, only:[:index, :show, :destory]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    get '/cart_items/top', to: 'cart_items#top'
    resources :orders, only:[:index, :new, :create]
    resources :addresses, only:[:create, :edit, :update, :destroy]
    
    resource :user, :only => [:edit, :show, :update] do
      get 'unsubscribe_confirm'
      patch 'unsubscribe'
    end

  end
  
  namespace :admins do
    resources :jenres, only:[:index, :create, :edit, :update, :destroy]
    resources :artists, only:[:index, :create, :edit, :update, :destroy]
    resources :labels, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show, :new, :create, :edit, :update, :destroy]
    resources :labels, only:[:index, :new, :create]
    resources :addresses, only:[:destroy]
    resources :users, only:[:index, :show, :edit, :update, :destroy]
    resources :orders, only:[:index, :show, :update]
  	root "items#index"
  end
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses, dependent: :destroy
  

  validates :last_name,length: {in: 1.. 15},format: { with: /\A\p{blank}*[^\p{katakana}\p{blank}ｧ-ﾝﾞﾟ]+\p{blank}*\z/}
  validates :first_name,length: {in: 1.. 15},format: { with: /\A\p{blank}*[^\p{katakana}\p{blank}ｧ-ﾝﾞﾟ]+\p{blank}*\z/}
  validates :kana_last_name,length: {in: 1.. 15},format: { with: /\A[\p{katakana}-]+\z/}
  validates :kana_first_name,length: {in: 1.. 15},format: { with: /\A[\p{katakana}-]+\z/}
  validates :phone, length: {in: 10.. 11}
  validates :postal_code, length: {in: 5.. 9}, format: { with: /\w/ }
  validates :address, presence: true
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
      before_action:authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @admin = current_admin
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    # binding.pry
    redirect_to admins_users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to admins_users_path 
  end
  
  private
    def user_params
      params.require(:user).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:phone,:postal_code,:address,:email)
    end
  
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
        before_action:authenticate_user!

    def edit
        @address = Address.find(params[:id])
    end
    
    def update
        address = Address.find(params[:id])
        address.update(address_params)
        redirect_to new_users_order_path
    end
    
    def destroy
        @address = Address.find(params[:id])
        @address.destroy
        redirect_to new_users_order_path
    end
    
    private
        def address_params
            params.require(:address).permit(:name, :postal_code, :address, :prefectures)
        end
end

app/controllers/users/cart_items_controller.rb
class Users::CartItemsController < ApplicationController
   before_action :authenticate_user!
   
   def top
   end
  
  def index
    @total_price = 500
    @item_total_price = 0
    @cart = current_user.cart_items
    # binding.pry
    @order = Order.new
    @order_detail = OrderDetail.new
    @cart.each do |cart|
      @item_total_price = cart.item.price * cart.amount
      @total_price += @item_total_price
    end
  end
  
  def create
        cart = CartItem.new(cart_item_params)
        cart.user_id = current_user.id 
        # p cart.errors.full_messages
      if current_user.cart_items.exists?(item_id: cart.item_id)
        update_cart_item = current_user.cart_items.find_by(item_id: cart.item_id)
        update_cart_item.amount += cart.amount
        update_cart_item.update(amount: update_cart_item.amount)
      else 
        cart.save
      end
      redirect_to users_cart_items_path  
  end
  
  def update
    cart = CartItem.find(params[:id])
    cart.amount = 1
    update_cart_item = current_user.cart_items.find_by(item_id: cart.item_id)
    update_cart_item.amount += cart.amount
    update_cart_item.update(amount: update_cart_item.amount)
    redirect_to users_cart_items_path
  end
  
  def destroy
    @item = CartItem.find(params[:id])
    @item.destroy
    redirect_to users_cart_items_path
  end
  
  private
    def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
    end
    
    def order_params
      params.require(:order).permit(:total_price)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController
    def index
        @item = Item.search(params[:search]).page(params[:page]).order(created_at: :desc)
    end
    
    def show
        @item = Item.find(params[:id])
        @cart = CartItem.new
        @a = 0
        
        @current_stock_array = []
        @item.stock.times do |amount|
            @current_stock_array << amount + 1
        
        end
        limit = 10
        @current_stock_array =  @item.stock > limit ? (1..limit).to_a : (1..@item.stock).to_a
    end
    
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to users_cart_items_path
  end
    
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
    before_action:authenticate_user!

    def index
        @order = current_user.orders
        @orders = @order.page(params[:page]).order(created_at: :desc)
    end
    
    def new
        @order = Order.new
        @user = current_user
        @address = Address.new
    end
    
    def create
        
        address = current_user.addresses.build

        if params[:a].to_i == -1
            address.name = current_user.name
            address.address = current_user.address
            address.postal_code = current_user.postal_code
        elsif params[:a].to_i == 0
            address.name = params[:name]
            address.address = params[:address]
            address.postal_code = params[:postal_code]
            address.prefectures = params[:prefectures]
            address.save
        else
            ad = Address.find(params[:a])
            address.name = ad.name
            address.address = ad.address
            address.postal_code = ad.postal_code
        end
        
        # binding.pry
        
        sum = 500
        order = Order.new
        order.address = address.address
        order.user_id = current_user.id
        order.postal_code = address.postal_code
        
         current_user.cart_items.each do |cart_item|
             sum += (cart_item.item.price*cart_item.amount)
         end
         order.total_price = sum
        #  binding.pry
        if order.save

            order.save_details(current_user)
            
            cart = current_user.cart_items
            # binding.pry
            cart.destroy_all
            redirect_to users_cart_items_top_path

        else
            redirect_to users_cart_items_path
        end
    end
    
    private
    
    
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @user = current_user
        @addresses = @user.addresses
        @a = 0
    end
    
    def edit
        @user = current_user
    end
    
    def update
        @user = current_user
        @user.update(user_params)
        redirect_to users_user_path(@user)
    end
    
    def unsubscribe_confirm
    end

  def unsubscribe
    current_user.destroy
    reset_session
    flash[:success] = "退会しました"
    redirect_to new_user_registration_path
  end
    
    
    private
    def user_params
        params.require(:user).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:phone,:postal_code,:address,:email)
    end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/addresses_helper.rb
module Users::AddressesHelper
end

app/helpers/users/artists_helper.rb
module Users::ArtistsHelper
end

app/helpers/users/cart_items_helper.rb
module Users::CartItemsHelper
end

app/helpers/users/disks_helper.rb
module Users::DisksHelper
end

app/helpers/users/items_helper.rb
module Users::ItemsHelper
end

app/helpers/users/jenres_helper.rb
module Users::JenresHelper
end

app/views/admins/users/edit.html.erb
<div class="container">
    <h2>ユーザ編集</h2>
    
        
        <%= form_with model: @user, url: admins_user_path(@user), local: true do |form| %>
            <div class="panel panel-default">
                <div class="user_form", style="margin: 0 auto; width: 400px">
                <p> 名前(姓・名)</p>
                <%= form.text_field :last_name %>
                <%= form.text_field :first_name %>
                
                <p> 名前(セイ・メイ) </p>
                <%= form.text_field :kana_last_name %>
                <%= form.text_field :kana_first_name %>
                
                <p> 郵便番号 </p>
                <%= form.text_field :postal_code %>
                
                <p> 住所 </p>
                <%= form.text_field :address %>
                
                <p> 電話番号 </p>
                <%= form.text_field :phone %>
                
                <p> メールアドレス </p>
                <%= form.text_field :email %>
                </div>
            </div>
            <div class="user_submit", style="float:right;">
                <%= form.submit "保存", class: "btn btn-success" %>
            </div>
        <% end %>
        
</div>

app/views/admins/users/index.html.erb
<div class="container">
 <table  class="table table-striped">
  <tr>
   <td>ユーザネーム</td>

   <td></td>
  </tr>
 
   <% @users.each do |user| %>

    <tr>
     <td><%= link_to user.last_name,admins_user_path(user) %></td>

     <td>
      <%= link_to "詳細", admins_user_path(user), class: "btn btn-success" %>
      <%= link_to "削除", admins_user_path(user), method: :delete, data: { "confirm" => "本当に削除しますか？" }, class: "btn btn-danger" %>
     </td>
    </tr>

   <% end %>
   <%= paginate(@users) %>
  </table>
 </div>

app/views/admins/users/show.html.erb
<div class="container">
<h2><%= @user.last_name %><%= @user.first_name %>さん</h2>
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
      <ul class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab">ユーザー詳細</a></li>
      <li><a href="#tab2" data-toggle="tab">登録住所一覧</a></li>
      <li><a href="#tab3" data-toggle="tab">購入履歴一覧</a></li>
    </ul>
    
    <div class="tab-content">
      <div id="tab1" class="tab-pane active">
        <div class="panel panel-primary", style = "text-align: center;">
        <p><h4>名前(漢字)</h4>  <%= @user.last_name %><%= @user.first_name %></p>
            
            
            
            <h4>名前(カナ)</h4>
            <%= @user.kana_last_name %>
            <%= @user.kana_first_name %>
            
            <h4>郵便番号</h4>
            <%= @user.postal_code %>
            
            <h4>住所</h4>
            <%= @user.address %>
            
            <h4>電話番号</h4>
            <%= @user.phone %>
            
            <h4>メールアドレス</h4>
            <%= @user.email %>

            <%= link_to "編集", edit_admins_user_path(@user), class: "btn btn-success"%>            
            <%= link_to "削除", admins_user_path(@user), method: :delete, data: { "confirm" => "本当に削除しますか？" }, class: "btn btn-danger" %>
      </div>
      </div>
      
      <div id="tab2" class="tab-pane">
          <div class="panel panel-primary", style = "text-align: center;">
            <% @user.addresses.each do |address| %>
                <hr>
                <%= address.prefectures %>
                <%= address.address %>
                <%= link_to "削除", users_address_path(address), method: :delete, data: { "confirm" => "本当に削除しますか？" }, class: "btn btn-danger" %>
            <% end %>
          </div>
      </div>
      
      <div id="tab3" class="tab-pane">
          
            <% @user.orders.each do |order| %>
            <div class="panel panel-primary", style = "text-align: center; height: 260px;">
                <div class="col-xs-4">
                    <table>
                    <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                    <tr>
                        <th>商品タイトル</th>
                        <th>:枚数:</th>
                        <th>金額</th>
                    </tr>
                    
                    <% order.order_details.each do |order_detail| %>
                    <tr>
                    <td><%= order_detail.item.title %></td>
                    <td><%= order_detail.cd_amount %></td>
                    <td>￥<%= order_detail.item.price %></td>
                    </tr>
                    <% end %></table>
                </div>
                
                <div class='col-xs-8'>
                    <p>注文番号: <%= order.id %></p>
                    
                    <p>ステータス</p>
                    <% if order.status == 0 %>
                        <p>商品準備中</p>
                    <% else %>
                        <p>出荷中</p>
                    <% end %>

                    <p>支払方法</p>
                    <% if order.payment == 0 %>
                        <p>代引き</p>
                    <% else %>
                        <p>銀行振り込み</p>
                    <% end %>
                    
                    <p>発送先: <%= order.postal_code %> <%= order.address %></p>
                    
                    <p>合計金額: ￥<%= order.total_price %></p>
                    
                    <%= link_to "show", admins_order_path(order), class: "btn btn-success" %>
                    
                </div>
                </div>
            <% end %>
      
      </div>
     </div>
    </div>
</div>

</div>