config/routes.rb
Rails.application.routes.draw do
     root 'users/items#index'
  namespace :users, :path => ""  do
    resources :items, only:[:index, :show, :destory]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    get '/cart_items/top', to: 'cart_items#top'
    resources :orders, only:[:index, :new, :create]
    resources :addresses, only:[:create, :edit, :update, :destroy]
    
    resource :user, :only => [:edit, :show, :update] do
      get 'unsubscribe_confirm'
      patch 'unsubscribe'
    end

  end
  
  namespace :admins do
    resources :jenres, only:[:index, :create, :edit, :update, :destroy]
    resources :artists, only:[:index, :create, :edit, :update, :destroy]
    resources :labels, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show, :new, :create, :edit, :update, :destroy]
    resources :labels, only:[:index, :new, :create]
    resources :addresses, only:[:destroy]
    resources :users, only:[:index, :show, :edit, :update, :destroy]
    resources :orders, only:[:index, :show, :update]
  	root "items#index"
  end
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details, dependent: :destroy
    belongs_to :user
    
    validates :total_price, presence: true
    validates :address, presence: true
    validates :payment, presence: true
    
    accepts_nested_attributes_for :order_details

    

    def save_details(user)
    	user.cart_items.each do |cart_item|
            
            item = OrderDetail.new
            item.item_id =  cart_item.item_id
            item.order_id = id
            item.cd_price = cart_item.item.price
            item.cd_amount = cart_item.amount
            item.save
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses, dependent: :destroy
  

  validates :last_name,length: {in: 1.. 15},format: { with: /\A\p{blank}*[^\p{katakana}\p{blank}ｧ-ﾝﾞﾟ]+\p{blank}*\z/}
  validates :first_name,length: {in: 1.. 15},format: { with: /\A\p{blank}*[^\p{katakana}\p{blank}ｧ-ﾝﾞﾟ]+\p{blank}*\z/}
  validates :kana_last_name,length: {in: 1.. 15},format: { with: /\A[\p{katakana}-]+\z/}
  validates :kana_first_name,length: {in: 1.. 15},format: { with: /\A[\p{katakana}-]+\z/}
  validates :phone, length: {in: 10.. 11}
  validates :postal_code, length: {in: 5.. 9}, format: { with: /\w/ }
  validates :address, presence: true
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
      before_action:authenticate_admin!

  def index
    @orders = Order.page(params[:page]).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admins_orders_path
  end
  
  private
   def order_params
     params.require(:order).permit(:status)
   end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
      before_action:authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @admin = current_admin
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    # binding.pry
    redirect_to admins_users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to admins_users_path 
  end
  
  private
    def user_params
      params.require(:user).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:phone,:postal_code,:address,:email)
    end
  
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
        before_action:authenticate_user!

    def edit
        @address = Address.find(params[:id])
    end
    
    def update
        address = Address.find(params[:id])
        address.update(address_params)
        redirect_to new_users_order_path
    end
    
    def destroy
        @address = Address.find(params[:id])
        @address.destroy
        redirect_to new_users_order_path
    end
    
    private
        def address_params
            params.require(:address).permit(:name, :postal_code, :address, :prefectures)
        end
end

app/controllers/users/cart_items_controller.rb
class Users::CartItemsController < ApplicationController
   before_action :authenticate_user!
   
   def top
   end
  
  def index
    @total_price = 500
    @item_total_price = 0
    @cart = current_user.cart_items
    # binding.pry
    @order = Order.new
    @order_detail = OrderDetail.new
    @cart.each do |cart|
      @item_total_price = cart.item.price * cart.amount
      @total_price += @item_total_price
    end
  end
  
  def create
        cart = CartItem.new(cart_item_params)
        cart.user_id = current_user.id 
        # p cart.errors.full_messages
      if current_user.cart_items.exists?(item_id: cart.item_id)
        update_cart_item = current_user.cart_items.find_by(item_id: cart.item_id)
        update_cart_item.amount += cart.amount
        update_cart_item.update(amount: update_cart_item.amount)
      else 
        cart.save
      end
      redirect_to users_cart_items_path  
  end
  
  def update
    cart = CartItem.find(params[:id])
    cart.amount = 1
    update_cart_item = current_user.cart_items.find_by(item_id: cart.item_id)
    update_cart_item.amount += cart.amount
    update_cart_item.update(amount: update_cart_item.amount)
    redirect_to users_cart_items_path
  end
  
  def destroy
    @item = CartItem.find(params[:id])
    @item.destroy
    redirect_to users_cart_items_path
  end
  
  private
    def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
    end
    
    def order_params
      params.require(:order).permit(:total_price)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController
    def index
        @item = Item.search(params[:search]).page(params[:page]).order(created_at: :desc)
    end
    
    def show
        @item = Item.find(params[:id])
        @cart = CartItem.new
        @a = 0
        
        @current_stock_array = []
        @item.stock.times do |amount|
            @current_stock_array << amount + 1
        
        end
        limit = 10
        @current_stock_array =  @item.stock > limit ? (1..limit).to_a : (1..@item.stock).to_a
    end
    
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to users_cart_items_path
  end
    
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
    before_action:authenticate_user!

    def index
        @order = current_user.orders
        @orders = @order.page(params[:page]).order(created_at: :desc)
    end
    
    def new
        @order = Order.new
        @user = current_user
        @address = Address.new
    end
    
    def create
        
        address = current_user.addresses.build

        if params[:a].to_i == -1
            address.name = current_user.name
            address.address = current_user.address
            address.postal_code = current_user.postal_code
        elsif params[:a].to_i == 0
            address.name = params[:name]
            address.address = params[:address]
            address.postal_code = params[:postal_code]
            address.prefectures = params[:prefectures]
            address.save
        else
            ad = Address.find(params[:a])
            address.name = ad.name
            address.address = ad.address
            address.postal_code = ad.postal_code
        end
        
        # binding.pry
        
        sum = 500
        order = Order.new
        order.address = address.address
        order.user_id = current_user.id
        order.postal_code = address.postal_code
        
         current_user.cart_items.each do |cart_item|
             sum += (cart_item.item.price*cart_item.amount)
         end
         order.total_price = sum
        #  binding.pry
        if order.save

            order.save_details(current_user)
            
            cart = current_user.cart_items
            # binding.pry
            cart.destroy_all
            redirect_to users_cart_items_top_path

        else
            redirect_to users_cart_items_path
        end
    end
    
    private
    
    
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @user = current_user
        @addresses = @user.addresses
        @a = 0
    end
    
    def edit
        @user = current_user
    end
    
    def update
        @user = current_user
        @user.update(user_params)
        redirect_to users_user_path(@user)
    end
    
    def unsubscribe_confirm
    end

  def unsubscribe
    current_user.destroy
    reset_session
    flash[:success] = "退会しました"
    redirect_to new_user_registration_path
  end
    
    
    private
    def user_params
        params.require(:user).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:phone,:postal_code,:address,:email)
    end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/addresses_helper.rb
module Users::AddressesHelper
end

app/helpers/users/artists_helper.rb
module Users::ArtistsHelper
end

app/helpers/users/cart_items_helper.rb
module Users::CartItemsHelper
end

app/views/users/orders/index.html.erb
<div class="container">

    
        <% @orders.each do |order| %>
             <div class="panel panel-default", style="height: 250px">
                 
                <div class='col-xs-4'>
                    <div><%= order.created_at.strftime('%Y/%m/%d') %></div>
                    
                        <div style="width:33%;float:left;">商品タイトル</div>
                        <div style="width:33%;float:left;">数</div>
                        <div style="width:33%;float:left;">合計金額</div>
                    
                    <% order.order_details.each do |order_detail| %>
                    
                        <div style="width:33%;float:left;"><%= order_detail.item.title %></div>
                        <div style="width:33%;float:left;"><%= order_detail.cd_amount %></div>
                        <div style="width:33%;float:left;"><p>￥<%= order_detail.item.price*order_detail.cd_amount %></p></div>
                    
                    <% end %>
                </div>
                
                <div class='col-xs-8'>
                    <p>注文番号:<%= order.id %></p>
                    
                    <p>ステータス:
                    <% if order.status == 0 %>
                        <p>商品準備中</p>
                    <% else %>
                        <p>出荷中</p>
                    <% end %>
                    </p>
                    
                    <p>支払方法
                    <% if order.payment == 0 %>
                        <p>代引き</p>
                    <% else %>
                        <p>銀行振り込み</p>
                    <% end %>
                    </p>
                    
                    <p>発送先:<%= order.postal_code %>-<%= order.address %></p>
                    
                    <p>合計金額:<%= order.total_price %></p>
                    
                </div>  
            </div>
        <% end %>
        <%= paginate(@orders) %>
  

</div>

app/views/users/orders/new.html.erb
<div class="container">
    
    <%= form_with url: users_orders_path, local: true do |form| %>
    <div class="panel panel-default", style="padding: 10px">
        <table>
        <p>配送</p>
        <hr>
        <br>
        <label>
            <%= radio_button_tag "a", -1 %>この住所を使う
        </label>
        <%= @user.postal_code %>
        <%= @user.address %>
        </br>
        
        <br>
        <% @user.addresses.each do |ad| %>
            <label>
                <%= radio_button_tag "a", ad.id %>この住所を使う
            </label>
            <br>
                <%= ad.name %>
                <%= ad.postal_code %>
                <%= ad.address %>
                <%= link_to "編集",edit_users_address_path(ad) %>
                <%= link_to "削除",users_address_path(ad), method: :delete %>
                </br>
        <% end %>
        </br>
        
        <br>
        <label>
             <%= radio_button_tag "a", 0 %>この住所を使う
        </label>
        

        <%= form.label "氏名" %>
        <%= form.text_field :name %>
        
        <%= form.label "郵便番号" %>
        <%= form.text_field :postal_code %>
        
        <%= form.label "都道府県" %>
        <%= form.select :prefectures, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"], :prompt => "選択してください" %>

        <%= form.label "住所" %>
        <%= form.text_field :address %>
        
        </br>
        </table>
        </div>

        <div class="panel panel-default", style="padding: 10px">
        <p>お支払い方法</p>
        <hr>
        <table style="margin-bottom: 10px">
        <br>
        <label>
             <%= radio_button_tag "payment", 0 %>代引き
        </label>
        </br>
        
        <br>
        <label>
             <%= radio_button_tag "payment", 1 %>銀行振り込み
        </label>
        </br>
        <tr>
                <th>銀行名</th>
                <td>xxxxxxxxx</td>
            </tr>
            <tr>
                <th>支店名</th>
                <td>xxxxxxxxx</td>
            </tr>
            <tr>
                <th>預金科目</th>
                <td>xxxxxxxxx</td>
            </tr>
            <tr>
                <th>口座番号</th>
                <td>xxxxxxxxx</td>
            </tr>
            <tr>
                <th>口座名義</th>
                <td>xxxxxxxxx</td>
            </tr>
            <tr>
                <th>振込名義</th>
                <td>xxxxxxxxx</td>
            </tr>
        </table>
        
        <%= form.submit "購入確定" %>
    </div>        
    <% end %>
    
</div>

app/views/users/orders/top.html.erb
<h1>ご注文ありがとうございました。</h1>