config/routes.rb
Rails.application.routes.draw do
     root 'users/items#index'
  namespace :users, :path => ""  do
    resources :items, only:[:index, :show, :destory]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    get '/cart_items/top', to: 'cart_items#top'
    resources :orders, only:[:index, :new, :create]
    resources :addresses, only:[:create, :edit, :update, :destroy]
    
    resource :user, :only => [:edit, :show, :update] do
      get 'unsubscribe_confirm'
      patch 'unsubscribe'
    end

  end
  
  namespace :admins do
    resources :jenres, only:[:index, :create, :edit, :update, :destroy]
    resources :artists, only:[:index, :create, :edit, :update, :destroy]
    resources :labels, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show, :new, :create, :edit, :update, :destroy]
    resources :labels, only:[:index, :new, :create]
    resources :addresses, only:[:destroy]
    resources :users, only:[:index, :show, :edit, :update, :destroy]
    resources :orders, only:[:index, :show, :update]
  	root "items#index"
  end
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_many :disks, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    has_many :order_details
    
    belongs_to :artist
    belongs_to :jenre
    belongs_to :label
    
    validates :title, presence: true
    validates :price, presence: true
    validates :stock, presence: true

    attachment :jacket_image
    
    accepts_nested_attributes_for :disks, reject_if: :all_blank, allow_destroy: true
    
    def self.search(search)
      if search
        Item.where(['title LIKE ?', "%#{search}%"])
      else
        Item.all
      end
    end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
      before_action:authenticate_admin!

    def index
        @item = Item.search(params[:search]).page(params[:page]).order(created_at: :desc)
    end

    def edit
        @item = Item.find(params[:id])
        @item.disks.build
        @disk = @item.disks.build
        @song = @disk.songs.build
        @artist = Artist.all
        @label = Label.all
        @jenre = Jenre.all
    end

    def show
        @item = Item.find(params[:id])
        @a = 0
    end

    def new
        @item = Item.new
        @disk = @item.disks.build
        @song = @disk.songs.build
        @artist = Artist.all
        @label = Label.all
        @jenre = Jenre.all
    end

    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to admins_items_path
        else
            @disk = @item.disks.build
            @song = @disk.songs.build
            @artist = Artist.all
            @label = Label.all
            @jenre = Jenre.all
            render  :new
        end
    end

    def update
        item = Item.find(params[:id])
        # binding.pry
        item.update(item_params)
        redirect_to admins_items_path
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to admins_items_path
    end
    
    private
    def item_params
        params.require(:item).permit(:artist_id, :label_id, :jenre_id, :title, :price, :status, :jacket_image, :stock,
                                      disks_attributes: [:id, :_destroy,
                                      songs_attributes: [:id, :_destroy, :title]])
    end

end

app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController
    def index
        @item = Item.search(params[:search]).page(params[:page]).order(created_at: :desc)
    end
    
    def show
        @item = Item.find(params[:id])
        @cart = CartItem.new
        @a = 0
        
        @current_stock_array = []
        @item.stock.times do |amount|
            @current_stock_array << amount + 1
        
        end
        limit = 10
        @current_stock_array =  @item.stock > limit ? (1..limit).to_a : (1..@item.stock).to_a
    end
    
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to users_cart_items_path
  end
    
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/users/items_helper.rb
module Users::ItemsHelper
end

app/views/admins/items/_disk_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="form-group">
    <%= link_to_remove_association "remove disk", f %>
  </div>

  <div class="items">
    <%= f.fields_for :songs do |song| %>
      <%= render 'song_fields', f: song %>
    <% end %>
    <div class="links">
      <%= link_to_add_association "add song", f, :songs %>
    </div>
  </div>
</div>

app/views/admins/items/_item.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="item_form", style="margin:0 auto; width: 400px;">
      
      <%= form_for [:admins, item] do |f| %>
      <div class="field">
      <p>アーティスト名　<%= f.select :artist_id, artist.collect {|p| [p.name, p.id]}, :prompt => "選択してください" %></p>
      
      <p>シングル/アルバム名　<%= f.text_field :title %></p>
    
      <p>ジャケット画像　<%= f.attachment_field :jacket_image %></p>
    
      <p>価格　<%= f.text_field :price %></p>
    
      <p>レーベル名　<%= f.select :label_id, label.collect {|p| [p.name, p.id]}, :prompt => "選択してください" %></p>
    
      <p>ジャンル名　<%= f.select :jenre_id, jenre.collect {|p| [p.name, p.id]}, :prompt => "選択してください" %></p>
    
      <p>ステータス　<%= f.select :status, ["販売中","販売停止"], :prompt => "選択してください" %></p>
    
      <p>在庫数　<%= f.number_field :stock %></p>
      </div>
      <h3>Disk</h3>
      <div id="disks">
           <%= f.fields_for :disks do |disk| %>
             <%= render 'disk_fields', f: disk %>
        <% end %>
        <div id="links">
    
          <%= link_to_add_association 'add disk',f, :disks, class: "btn btn-success" %>
        </div>
    </div>
      <%= f.submit "登録" %>
      
      <% end %>
    
  </div>
</div>
</div>

app/views/admins/items/_song_fields.html.erb
<div class="nested-fields form-inline">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= link_to_remove_association "削除", f %>
  </div>
</div>

app/views/admins/items/edit.html.erb
 <h3>商品編集</h3>
    <%= render 'admins/items/item', item: @item, artist: @artist, label: @label, jenre: @jenre %>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <%= link_to "新規登録", new_admins_item_path, class: "btn btn-info" %>
    <hr>
    <% @item.each do |item| %>
              <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
        </div>
        <div class="panel-body">
            <div class="row">
              <div class="col-sm-6">
                <%= attachment_image_tag item, :jacket_image, :fill, 150, 150, fallback: "/images/no_image.jpg", size: "150x150" %>
              </div>
              <div class="col-sm-6">
                <h3><%= item.title %> - <%= item.artist.name %></h3>
                <p>在庫数: <%= item.stock %></p>
                <p><%= item.status ? "販売中" : "売り切れ" %></p>


                <%= link_to "show", admins_item_path(item), class: "btn btn-success" %>
              </div>
            </div>

        </div>
      </div>
      </div>

    <% end %>
    <%= paginate(@item) %>
  </div>
</div>

app/views/admins/items/new.html.erb
    <% if @item.errors.any? %>
    	<% @item.errors.full_messages.each do |message| %>
    	<div style="color: red; margin-left: 10px;">
    		<li>
    		<%= message %>
    		</li>
    	</div>
    	<% end %>
    <% end %>
    <%= render 'admins/items/item', item: @item, artist: @artist, label: @label, jenre: @jenre %>

app/views/admins/items/show.html.erb
<%= render 'layouts/item_show', item: @item, a: @a %>